version: '2'
services:
  postgres-db:
    image: 52north/sos-empty-postgres:1.0.0
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sos

  sos-service:
    image: 52north/sos:4.3.7
    ports:
      - 8080:8080
    links:
      - postgres-db:postgres
