version: '2'
services:
  postgres-db-empty:
    image: mdillon/postgis:9.5
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sos
  sos-service:
    image: 52north/sos:4.3.7
    ports:
      - 8080:8080
    links:
      - postgres-db-empty:postgres
