version: '2'
services:
  sos-example-postgres:
    image: 52north/sos-example-postgres:4.3.7
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sos
  sos-service:
    image: 52north/sos-configured:4.3.7
    ports:
      - 8080:8080
    links:
      - sos-example-postgres:postgres
