FROM 52north/sos:4.3.8
MAINTAINER Matthes Rieke <m.rieke@52north.org>

# Project: https://github.com/52North/sos

COPY sos-config/configuration.db $CATALINA_HOME/webapps/52n-sos-webapp/
COPY sos-config/datasource.properties $CATALINA_HOME/webapps/52n-sos-webapp/WEB-INF
